FROM registry.redhat.io/ansible-automation-platform-25/de-supported-rhel9:latest

USER root

COPY requirements.yaml /tmp/requirements.yaml
RUN ansible-galaxy collection install -r /tmp/requirements.yaml \
      --collections-path /usr/share/ansible/collections \
    && rm /tmp/requirements.yaml

USER 1000
