apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-config
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycloak-config
  namespace: rhdh
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["rhdh-keycloak-client-secret"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-config
  namespace: rhdh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keycloak-config
subjects:
  - kind: ServiceAccount
    name: keycloak-config
    namespace: {{ .Values.namespace }}
