---
eda_decision_environments:
  - name: Default Decision Environment
    description: Default DE for EDA rulebook activations (includes servicenow.itsm)
    image_url: "image-registry.openshift-image-registry.svc:5000/aap-shared-builds/de-ansibleforge:latest"
    organization: Default
