apiVersion: v1
kind: ServiceAccount
metadata:
  name: aap-cluster-admin
  namespace: aap
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aap-cluster-admin
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: aap-cluster-admin
    namespace: aap
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aap-cluster-admin-token-creator
  namespace: aap
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    resourceNames: ["aap-cluster-admin"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aap-cluster-admin-token-creator
  namespace: aap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aap-cluster-admin-token-creator
subjects:
  - kind: ServiceAccount
    name: aap-keycloak-sso
    namespace: aap
