{{- $clusterDomain := .Values.clusterDomain }}
{{- if not $clusterDomain }}
{{- $ingressConfig := lookup "config.openshift.io/v1" "Ingress" "" "cluster" }}
{{- if and $ingressConfig $ingressConfig.spec }}
{{- $clusterDomain = $ingressConfig.spec.domain }}
{{- end }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: aap-lightspeed-chatbot-config
  namespace: aap
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  rcsconfig.yaml: |
    llm_providers:
      - name: openai
        type: openai
        url: "https://api.openai.com/v1"
        credentials_path: /etc/rcs/openai_api_key.txt
        models:
          - name: gpt-4o

    rcs_config:
      default_provider: openai
      default_model: gpt-4o
