apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lightspeed-openai-api-key
  namespace: aap
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: lightspeed-openai-api-key
    template:
      engineVersion: v2
      data:
        openai_api_key.txt: "{{ `{{ .api_key }}` }}"
  data:
    - secretKey: api_key
      remoteRef:
        key: secret/openai
        property: api_key
