apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lightspeed-chatbot-config
  namespace: aap
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: aap-lightspeed-chatbot-config
    template:
      engineVersion: v2
      data:
        chatbot_model: gpt-5.4
        chatbot_url: "https://api.openai.com/v1"
        chatbot_token: "{{ `{{ .api_key }}` }}"
        chatbot_llm_provider_type: openai
        aap_gateway_url: "http://aap"
        aap_controller_url: "http://aap-controller-service"
  data:
    - secretKey: api_key
      remoteRef:
        key: secret/openai
        property: api_key
