---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleCredential
metadata:
  name: vault-lookup
  namespace: aap
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  connection_secret: aap-gateway-oauth2-token-secret
  name: Vault Lookup
  organization: Default
  type: HashiCorp Vault Secret Lookup
  inputs: |
    {
      "url": "http://vault.vault.svc:8200",
      "default_auth_path": "kubernetes",
      "kubernetes_role": "aap-controller",
      "api_version": "v2"
    }
