{{- $clusterDomain := .Values.clusterDomain }}
{{- if not $clusterDomain }}
{{- $ingressConfig := lookup "config.openshift.io/v1" "Ingress" "" "cluster" }}
{{- if and $ingressConfig $ingressConfig.spec }}
{{- $clusterDomain = $ingressConfig.spec.domain }}
{{- end }}
{{- end }}
{{- $oauthSecret := lookup "v1" "Secret" "aap" "aap-gateway-oauth2-token-secret" }}
{{- if and $clusterDomain $oauthSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: aap-resource-operator-connection
  namespace: aap
  annotations:
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
stringData:
  host: "https://aap-aap.{{ $clusterDomain }}"
data:
  token: {{ index $oauthSecret.data "token" }}
---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleCredential
metadata:
  name: vault-lookup
  namespace: aap
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  connection_secret: aap-resource-operator-connection
  name: Vault Lookup
  organization: Default
  type: HashiCorp Vault Secret Lookup
  inputs: |
    {
      "url": "http://vault.vault.svc:8200",
      "default_auth_path": "kubernetes",
      "kubernetes_role": "aap-controller",
      "api_version": "v2"
    }
{{- end }}
