---
- name: Provision VM on ServiceNow catalog request
  hosts: all
  sources:
    - servicenow.itsm.records:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        table: sc_req_item
        sysparm_query: "cat_item=2c160bb0c3f33210dd6df7fdd401311f^state=1"
        interval: 30
        remote_servicenow_timezone: GMT
  rules:
    - name: New Virtual Machine request — launch provisioning
      condition: event.sys_id is defined
      throttle:
        once_within: 1 minutes
        group_by_attributes:
          - event.sys_id
      action:
        run_job_template:
          name: "VM Provision - EC2"
          organization: Default
          job_args:
            extra_vars:
              ritm_number: "{{ event.number }}"
              ritm_sys_id: "{{ event.sys_id }}"

- name: Decommission VM on ServiceNow catalog request
  hosts: all
  sources:
    - servicenow.itsm.records:
        instance:
          host: "{{ SN_HOST }}"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        table: sc_req_item
        sysparm_query: "cat_item=b1995e0ac33f7210dd6df7fdd40131cb^state=1"
        interval: 30
        remote_servicenow_timezone: GMT
  rules:
    - name: Decommission VM request — launch deprovisioning
      condition: event.sys_id is defined
      throttle:
        once_within: 1 minutes
        group_by_attributes:
          - event.sys_id
      action:
        run_job_template:
          name: "VM Deprovision - EC2"
          organization: Default
          job_args:
            extra_vars:
              ritm_number: "{{ event.number }}"
              ritm_sys_id: "{{ event.sys_id }}"
