---
version: 3
images:
  base_image:
    name: registry.access.redhat.com/ubi9/ubi:latest
dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt
  exclude:
    system:
      - openshift-clients
  system:
    - git
    - python3-pip
    - python3-setuptools
    - systemd-devel
    - openldap-devel
    - gcc
    - gcc-c++
    - python3-devel
    - terraform
additional_build_files:
  - src: hashicorp.repo
    dest: configs
additional_build_steps:
  prepend_galaxy:
    - RUN dnf install -y git && dnf clean all
  prepend_builder:
    - ADD _build/configs/hashicorp.repo /etc/yum.repos.d/hashicorp.repo
  prepend_final:
    - ADD _build/configs/hashicorp.repo /etc/yum.repos.d/hashicorp.repo
    - RUN curl -sL https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz | tar -xz -C /usr/local/bin oc kubectl
