{{- $clusterDomain := .Values.clusterDomain }}
{{- if not $clusterDomain }}
{{- $ingressConfig := lookup "config.openshift.io/v1" "Ingress" "" "cluster" }}
{{- if and $ingressConfig $ingressConfig.spec }}
{{- $clusterDomain = $ingressConfig.spec.domain }}
{{- end }}
{{- end }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gitea
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  host: gitea.{{ $clusterDomain }}
  to:
    kind: Service
    name: gitea
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
