apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rhdh-aap-token
  namespace: rhdh
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: rhdh-aap-token
  data:
    - secretKey: token
      remoteRef:
        key: secret/aap-rhdh
        property: token
