---
keycloak_client_scopes:
  - name: profile
    protocol: openid-connect
    attributes:
      include.in.token.scope: "true"
      display.on.consent.screen: "true"
    protocolMappers:
      - name: username
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        config:
          claim.name: preferred_username
          user.attribute: username
          id.token.claim: "true"
          access.token.claim: "true"
          userinfo.token.claim: "true"
          jsonType.label: String
      - name: full name
        protocol: openid-connect
        protocolMapper: oidc-full-name-mapper
        config:
          id.token.claim: "true"
          access.token.claim: "true"
          userinfo.token.claim: "true"
      - name: given name
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        config:
          claim.name: given_name
          user.attribute: firstName
          id.token.claim: "true"
          access.token.claim: "true"
          userinfo.token.claim: "true"
          jsonType.label: String
      - name: family name
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        config:
          claim.name: family_name
          user.attribute: lastName
          id.token.claim: "true"
          access.token.claim: "true"
          userinfo.token.claim: "true"
          jsonType.label: String

  - name: email
    protocol: openid-connect
    attributes:
      include.in.token.scope: "true"
      display.on.consent.screen: "true"
    protocolMappers:
      - name: email
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        config:
          claim.name: email
          user.attribute: email
          id.token.claim: "true"
          access.token.claim: "true"
          userinfo.token.claim: "true"
          jsonType.label: String
      - name: email verified
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        config:
          claim.name: email_verified
          user.attribute: emailVerified
          id.token.claim: "true"
          access.token.claim: "true"
          userinfo.token.claim: "true"
          jsonType.label: boolean

  - name: roles
    protocol: openid-connect
    attributes:
      include.in.token.scope: "false"
    protocolMappers:
      - name: realm roles
        protocol: openid-connect
        protocolMapper: oidc-usermodel-realm-role-mapper
        config:
          claim.name: realm_access.roles
          multivalued: "true"
          id.token.claim: "true"
          access.token.claim: "true"
          userinfo.token.claim: "true"
          jsonType.label: String
      - name: client roles
        protocol: openid-connect
        protocolMapper: oidc-usermodel-client-role-mapper
        config:
          claim.name: "resource_access.${client_id}.roles"
          multivalued: "true"
          id.token.claim: "true"
          access.token.claim: "true"
          userinfo.token.claim: "true"
          jsonType.label: String

  - name: web-origins
    protocol: openid-connect
    attributes:
      include.in.token.scope: "false"
    protocolMappers:
      - name: allowed web origins
        protocol: openid-connect
        protocolMapper: oidc-allowed-origins-mapper
        config: {}

  - name: groups
    protocol: openid-connect
    attributes:
      include.in.token.scope: "true"
      display.on.consent.screen: "false"
    protocolMappers:
      - name: groups
        protocol: openid-connect
        protocolMapper: oidc-group-membership-mapper
        config:
          claim.name: groups
          full.path: "false"
          id.token.claim: "true"
          access.token.claim: "true"
          userinfo.token.claim: "true"

keycloak_default_scopes:
  - profile
  - email
  - roles
  - web-origins
