{{- if .Values.clusterName }}
{{- $secretKey := printf "%s/keycloak" .Values.clusterName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sso-monitor-credentials
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: sso-monitor-credentials
  data:
  - secretKey: test-user-password
    remoteRef:
      key: {{ $secretKey }}
      property: sysadmin-password
  {{- range $name, $svc := .Values.services }}
  {{- if and $svc.enabled (eq $name "gitlab") }}
  - secretKey: gitlab-client-secret
    remoteRef:
      key: {{ $secretKey }}
      property: gitlab-client-secret
  {{- end }}
  {{- if and $svc.enabled (eq $name "ocp") }}
  - secretKey: ocp-client-secret
    remoteRef:
      key: {{ $secretKey }}
      property: ocp-client-secret
  {{- end }}
  {{- end }}
{{- end }}
