{{- if .Values.clusterName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-oidc-client-secret
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: vault-oidc-client-secret
  data:
  - secretKey: client-secret
    remoteRef:
      key: {{ .Values.clusterName }}/keycloak
      property: vault-client-secret
{{- end }}
