FROM registry.access.redhat.com/ubi9/go-toolset:latest AS builder
USER root

RUN curl -sL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq && chmod +x /usr/local/bin/yq

COPY . /registry

RUN git clone https://github.com/devfile/registry-support.git /registry-support
# Patch build script to create last_modified.json before index-generator runs
RUN sed -i '/index-generator/i [ -f "$outputFolder/last_modified.json" ] || echo "{}" > "$outputFolder/last_modified.json"' \
    /registry-support/build-tools/build.sh
RUN /registry-support/build-tools/build.sh /registry /build

FROM quay.io/devfile/devfile-index-base:next

COPY --from=builder /build /registry
