name: "DNS: Deploy Terraform State Backend"

on:
  workflow_dispatch:
  workflow_call:

permissions:
  id-token: write
  contents: read

env:
  AWS_ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActions-${{ github.repository_owner }}-${{ github.event.repository.name }}

jobs:
  deploy:
    name: Deploy CloudFormation Stack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: us-east-2

      - name: Deploy tfstate-backend stack
        run: |
          aws cloudformation deploy \
            --stack-name tfstate-backend \
            --template-file ocp/terraform/dns/tfstate-backend.cfn.yaml \
            --no-fail-on-empty-changeset
